<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\chiffrement.ico</ApplicationIcon>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\chiffrement.png" />
    <None Remove="Assets\FindInFile.png" />
    <None Remove="Assets\NewItem.png" />
    <None Remove="Assets\OpenFile.png" />
    <None Remove="Assets\Redo.png" />
    <None Remove="Assets\ReplaceAll.png" />
    <None Remove="Assets\Save.png" />
    <None Remove="Assets\Undo.png" />
    <None Remove="chiffrement.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\chiffrement.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\chiffrement.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\FindInFile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\NewItem.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\OpenFile.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Redo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\ReplaceAll.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Save.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Undo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="chiffrement.png" />
  </ItemGroup>

</Project>
